### PR TITLE
Get PETSc loading again with Julia 1.11

### PR DESCRIPTION
**Pull request by ViralBShah**
The purpose of this PR is to get PETSc loading again, and to pass as many tests as possible.

The extent of commented out tests shows the damage that needs fixing.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@boriskaus I think with this, one can at least load the package without errors and warnings. I suggest we merge this into master, and then incrementally get all the tests working again.

**Comment by boriskaus** [comment]
thanks, does this autowrap the library?

**Comment by ViralBShah** [comment]
No that is a separate PR that is open. This is just doing the minimal to get the existing package loading. Note various tests are commented out.

**Comment by boriskaus** [comment]
ok, I'm 

Note that this branch https://github.com/JuliaParallel/PETSc.jl/tree/jek/dmstag has autowrap functions that can perhaps be used again

**Comment by ViralBShah** [comment]
I have a few other tests I am enabling. Will do that and merge.

**Comment by ViralBShah** [comment]
Now only a small number of tests are commented out. I don't know what is happening with Windows, but that seems like some kind of MPI issue. I'll open a separate issue for that.

The Documentation has lots of duplicate function issues, but I am not sure how to fix them all. Not an issue for now.

**Comment by ViralBShah** [comment]
> ok, I'm fine merging this (I guess the tests should pass though, or we only support the lts)
> 
> Note that this branch https://github.com/JuliaParallel/PETSc.jl/tree/jek/dmstag has autowrap functions that can perhaps be used again

I opened that closed PR again to leave it as a reminder. I am not a user of PETSc really, so this may be more work than I can help with - but I'll give it a shot. 

For now, the package is working, and it will be nice to reinstate all the tests and get Windows and docs working again too.

**Pull request merged**
