### PR TITLE
Fix PetscDestroy for TS and add test

### PR DESCRIPTION
**Pull request by kshyatt**
If you tried calling `isfinalized` it would break in a bunch of ways. Seems to be working now!

### CODE REVIEW

**Comment by JaredCrean2** [comment]
I'm glad you caught this.  Once all the tests pass I'll merge it.

**Comment by kshyatt** [comment]
I think this is dying on an unrelated test.

**Comment by kshyatt** [comment]
Sorry, I found another really easy test to write so I did!

**Comment by JaredCrean2** [comment]
This passed on the 0.4 release branch, which is good enough for me, combined with the `abs()` test from the other PR.  Merging

**Pull request merged**
