### PR TITLE
Update ci.yml for Mac aarch64 and use Julia-actions/cache to improve caching

### PR DESCRIPTION
**Pull request by ViralBShah**
`macOS-latest` is now aarch64 - so separate out that build recipe in an include to make sure it picks the right architecture. Otherwise, it is just testing x64 in emulation on ARM.

macOS-13 is x64 (but I am not sure if it is native or not). We could probably drop that too, since Apple stopped shipping those a few years ago - but people do still have them.

Also changing the version to test with `1` which tests with the latest stable release. Running `lts` only on linux should suffice to ensure we don't accidentally break it. This will all reduce CI load while the package is under heavy development.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@boriskaus Are you ok with this? If so, let's merge when green.

**Comment by ViralBShah** [comment]
On Julia 1.11, I routinely see test failures after DM Vectors and Coordinates. It feels like some kind of race condition, since rerunning the workflow often helps.

```
DM Vectors and Coordinates |  360    360  0.8s
free(): invalid next size (normal)
[2012] signal 6 (-6): Aborted
in expression starting at /home/runner/work/PETSc.jl/PETSc.jl/test/test_dmstag.jl:314
```

**Comment by boriskaus** [comment]
Yes I noticed this too and wonder if it is only in test_dmstag

**Comment by ViralBShah** [comment]
It has always been in `test_dmstag` every time I saw it. 

The new `julia-actions/cache` seems to be working nicely and shaving off some CI time.

**Pull request merged**
