### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by boriskaus**
This fixes the remaining tests in `main`

### CODE REVIEW

**Comment by ViralBShah** [comment]
Is it possible to run the Windows tests without MPI - or is MPI pretty much integral to everything - and it is impossible to test without MPI?

**Comment by boriskaus** [comment]
it is indeed my impression that MPI is quite central to it all. I think we better invest the time to get MicrosoftMPI working again (we encounter the same runtime bug as `HDF5_jll`)

**Comment by ViralBShah** [comment]
Do you have a link handy for the MicrosoftMPI issue?

**Comment by boriskaus** [comment]
This is identical to what I encountered with petsc:

https://github.com/JuliaPackaging/Yggdrasil/blob/868d8ba1f8a5f802567d42df6a37e8fd54a92d35/H/HDF5/build_tarballs.jl#L137

**Comment by ViralBShah** [comment]
This is the issue discussing in detail: https://github.com/JuliaPackaging/Yggdrasil/issues/8523

**Pull request merged**
