### PR TITLE
Allow for custom petsc builds

### PR DESCRIPTION
**Pull request by jkozdon**
I've attempted to adapt the code to allow for custom build of PETSc as well as multiple libraries (to allow for single, double, and complex numbers).

The idea is to set a colon separated environment variable `JULIA_PETSC_LIBRARY` which contains the full path to libraries, for example
```
JULIA_PETSC_LIBRARY=/path/to/double.so:/path/to/single.so
```

Note that this PR builds on #112, but since I am not sure I did this 100% the right way I decided to leave them as separate PRs. The main changes associated with this PR are the ones in `src/lib.jl`

One thing I am not sure the best way to do is test this...

### CODE REVIEW

**Comment by jkozdon** [comment]
@bmxam I was wondering if something like this would allow you to merge your [`PetscWrap.jl`](https://github.com/bmxam/PetscWrap.jl) efforts with `PETSc.jl`? Would be nice to have a single Julia PETSc wrapper package for everyone to use.

`GridapPETSc.jl` seems to be wrapper that is furthest along, but is very specific to the `Gridap.jl` package.

Thoughts?

**Comment by bmxam** [comment]
Hi,
Merging with PETSc.jl in a (near?) future is indeed my intention. I have to check again why I started my own wrapper aside. I'll test your new implementation and will come back to you as soon as I can (= eventually a few weeks).
Anyway, my first concern is too keep compatibility with SlepcWrap.jl; since this is the true package I am interested in.

**Comment by jkozdon** [comment]
No problem. I am not the package maintainer and I'm fairly new to playing with PETSc in general (considering it for a project and would like to do it through Julia if I do use it).

PETSc.jl and GridappPetsc are nice in that they provide the binaries builder which is nice for getting your toes wet. Your package is nice in that it allows more flexibility with PETSc build options.

**Comment by jkozdon** [comment]
The more I've been playing with this, I've wondering if it's really a good idea to allow the loading of multiple petsc libraries. You could have a situation where you have two `Float64` libraries one for `Int32` and one for `Int64` and (I assume) that one must be careful that data from one is not passed to the other.

The solution is probably to instead of typing everything on `PetscScalar` the tuple of values `(PetscScalar, PetscReal, PetscInt)`, and only allow one of each library triple to be loaded.

I imagine the use cases for having several PETSc libraries loaded sides by side are pretty minimal too.

**Comment by simonbyrne** [comment]
Support for multiple libraries predates my involvement (@stevengj mentioned it in #6), so I just tried to preserve it.

**Comment by jkozdon** [comment]
superseded by #117

**Pull request closed without merging**
