### PR TITLE
Added some docs for TS's options

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by JaredCrean2** [comment]
I'm not sure we should be documenting PETSc options as part of the julia wrappers.  Having 2 sets of documentation (Petsc's and ours) makes inconsistencies much more likely.

**Comment by kshyatt** [comment]
I added this mostly for consistency with `KSP`, since we have a big opts table there. I can shrink it down with a link to the relevant PETSc webpage?

**Comment by JaredCrean2** [comment]
Sounds good

**Comment by kshyatt** [comment]
Better?

**Comment by JaredCrean2** [comment]
Build failure looks unrelated.  Merging.

**Pull request merged**
