### PR TITLE
CI update

### PR DESCRIPTION
**Pull request by boriskaus**
This is an attempt to get CI to pass with the current version

### CODE REVIEW

**Comment by boriskaus** [comment]
I'm not sure why this is failing; it works fine on my local machine (macOS aarch64)

**Comment by boriskaus** [comment]
@ViralBShah All `MPI` tests fail in the CI, but work fine locally. A simple "hello world" MPI test does work, so it doesn't seem to be because of MPI itself.
As far as I can tell, the correct `MPICH_jll` is being employed.
Any idea?

**Comment by ViralBShah** [comment]
I have been noticing the same thing. One thing is that the build complains it is built with OpenMPI but we are using MPICH. The other thing is that we are unable to use the latest MPICH.

Perhaps @eschnett can help us with MPI here?

**Comment by boriskaus** [comment]
The problem with MPICH was solved last week thanks to @vchuravy and @giordano and only occured if the `PATH` environmental variable was empty. As far as I can tell, we here use the working version of `MPICH`.

Where do you see that PETSc was build with OpenMPI? That would indeed be a problem - it should be using the MPICH build instead.

**Comment by boriskaus** [comment]
Problem solved. Turns out to be that one should add
```Julia
using PETSc
```
at the beginning of  `runtests.jl`...

**Comment by boriskaus** [comment]
I am deactivating CI on windows because the `PETSc_jll` binaries for windows were compiled without `MPI` support (it did compile with `MicrosoftMPI`, but we always get runtime errors). Perhaps someone motivated can solve this again at some stage (it did work at some point in the past), and we can allow windows again.

Until that stage, windows users can simply install `WSL` on their machine and run `PETSc.jl` though windows. This will also give access to additional external packages.

**Comment by ViralBShah** [comment]
> Where do you see that PETSc was build with OpenMPI? That would indeed be a problem - it should be using the MPICH build instead.

I suspect I saw that in some CI logs, which would be very hard to find. If I see it again, I'll open a new issue.

**Comment by boriskaus** [comment]
> 
> I suspect I saw that in some CI logs, which would be very hard to find. If I see it again, I'll open a new issue.


ok. It appears to be solved meanwhile, so I'll merge this PR.

**Pull request merged**
